Description: >
  Marietta Ngwe Akumbom | Udacity Cloud DevOps Nanodegree
  Deploy a high-availability web app using CloudFormation
  User roles

Resources:
  

  S3ReadWriteRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: S3ReadWritePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                 - s3:PutObject
                 - s3:GetObject
                 - s3:ListBucket
                Resource: arn:aws:s3:::*
                
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref S3ReadWriteRole

Outputs:
  IAMProfileInstance:
    Description: reference to instance profile
    Value: !Ref InstanceProfile
    Export:
      Name: InstanceProfile