Description: >
  Marietta Ngwe Akumbom | Udacity Cloud DevOps Nanodegree
  Deploy a high-availability web app using CloudFormation
  User roles

Resources:
  

  S3ReadOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: S3ReadOnlyAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - s3:Get*
                  - s3:List*
                Resource: 
                  - arn:aws:s3:::udacity-cfn-bucket
                  - arn:aws:s3:::udacity-cfn-bucket/*
                
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref S3ReadOnlyRole

Outputs:
  IAMProfileInstance:
    Description: reference to instance profile
    Value: !Ref InstanceProfile
    Export:
      Name: InstanceProfile